export const movieActionTypes = {
  FETCH_GENRES: "FETCH_GENRES",
  FETCH_GENRES_ERROR: "FETCH_GENRES_ERROR",
  FETCH_GENRES_SUCCESS: "FETCH_GENRES_SUCCESS",
  FETCH_GENRES_REQUEST: "FETCH_GENRES_REQUEST",

  FETCH_TRENDING: "FETCH_TRENDING",
  FETCH_TRENDING_ERROR: "FETCH_TRENDING_ERROR",
  FETCH_TRENDING_SUCCESS: "FETCH_TRENDING_SUCCESS",
  FETCH_TRENDING_REQUEST: "FETCH_TRENDING_REQUEST",

  FETCH_UPCOMING: "FETCH_UPCOMING",
  FETCH_UPCOMING_ERROR: "FETCH_UPCOMING_ERROR",
  FETCH_UPCOMING_SUCCESS: "FETCH_UPCOMING_SUCCESS",
  FETCH_UPCOMING_REQUEST: "FETCH_UPCOMING_REQUEST",
};

export const userActionTypes = {
  TOGGLE_TRENDING_TIME_WINDOW: "TOGGLE_TRENDING_TIME_WINDOW",
}
