export const movieActionTypes = {
  FETCH_GENRES: "FETCH_GENRES",
  FETCH_GENRES_ERROR: "FETCH_GENRES_ERROR",
  FETCH_GENRES_SUCCESS: "FETCH_GENRES_SUCCESS",
  FETCH_GENRES_REQUEST: "FETCH_GENRES_REQUEST",

  FETCH_TRENDING: "FETCH_TRENDING",
  FETCH_TRENDING_ERROR: "FETCH_TRENDING_ERROR",
  FETCH_TRENDING_SUCCESS: "FETCH_TRENDING_SUCCESS",
  FETCH_TRENDING_REQUEST: "FETCH_TRENDING_REQUEST",

  FETCH_UPCOMING: "FETCH_UPCOMING",
  FETCH_UPCOMING_ERROR: "FETCH_UPCOMING_ERROR",
  FETCH_UPCOMING_SUCCESS: "FETCH_UPCOMING_SUCCESS",
  FETCH_UPCOMING_REQUEST: "FETCH_UPCOMING_REQUEST",

  FETCH_DETAIL: "FETCH_DETAIL",
  FETCH_DETAIL_ERROR: "FETCH_DETAIL_ERROR",
  FETCH_DETAIL_SUCCESS: "FETCH_DETAIL_SUCCESS",
  FETCH_DETAIL_REQUEST: "FETCH_DETAIL_REQUEST",

  FETCH_WATCH_PROVIDERS: "FETCH_WATCH_PROVIDERS",
  FETCH_WATCH_PROVIDERS_ERROR: "FETCH_WATCH_PROVIDERS_ERROR",
  FETCH_WATCH_PROVIDERS_SUCCESS: "FETCH_WATCH_PROVIDERS_SUCCESS",
  FETCH_WATCH_PROVIDERS_REQUEST: "FETCH_WATCH_PROVIDERS_REQUEST",

  FETCH_CREDITS: "FETCH_CREDITS",
  FETCH_CREDITS_ERROR: "FETCH_CREDITS_ERROR",
  FETCH_CREDITS_SUCCESS: "FETCH_CREDITS_SUCCESS",
  FETCH_CREDITS_REQUEST: "FETCH_CREDITS_REQUEST",

  FETCH_SIMILAR_MOVIES: "FETCH_SIMILAR_MOVIES",
  FETCH_SIMILAR_MOVIES_ERROR: "FETCH_SIMILAR_MOVIES_ERROR",
  FETCH_SIMILAR_MOVIES_SUCCESS: "FETCH_SIMILAR_MOVIES_SUCCESS",
  FETCH_SIMILAR_MOVIES_REQUEST: "FETCH_SIMILAR_MOVIES_REQUEST",
};

export const userActionTypes = {
  TOGGLE_TRENDING_TIME_WINDOW: "TOGGLE_TRENDING_TIME_WINDOW",
}
